services:
  bot:
    build:
      context: .
    image: notifications_bot:latest
    container_name: notifications_bot-bot-1
    restart: always

    # Переменные окружения берём из .env
    env_file:
      - .env
    environment:
      # На всякий случай прокидываем ключевые переменные
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - TZ=${TZ}
      - DB_PATH=/data/bot.db

    # Безопасность: корневая ФС только для чтения
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    # Куда можно писать
    volumes:
      - ./data:/data
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/tmp

    # Запускать контейнер от вашего пользователя (UID/GID заданы в .env)
    user: "${UID}:${GID}"

    # Мягкое завершение, чтобы не ловить exit 137
    stop_signal: SIGINT
    stop_grace_period: 60s

    # Ограничения и лог-ротация (под VPS с малой RAM)
    mem_limit: 256m
    memswap_limit: 1g
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    # Healthcheck: проверяем доступность Telegram API и что вебхук отключён
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - << 'PY'\nimport os,sys,urllib.request,json\nbt=os.getenv('BOT_TOKEN')\ntry:\n  me=json.load(urllib.request.urlopen(f'https://api.telegram.org/bot{bt}/getMe',timeout=10))\n  info=json.load(urllib.request.urlopen(f'https://api.telegram.org/bot{bt}/getWebhookInfo',timeout=10))\n  url=info.get('result',{}).get('url','')\n  sys.exit(0 if me.get('ok') and not url else 1)\nexcept Exception:\n  sys.exit(1)\nPY"
        ]
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 25s
